<a href="https://colab.research.google.com/github/amarbtsingh/first-contributions/blob/main/00_PyTorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

Creating Tensors

Scalar

In [2]:
scalar = torch.tensor(7) # number 7 is being initialised as a scalar

print(scalar)

scalar.ndim

print(type(scalar))


tensor(7)
<class 'torch.Tensor'>


Get tensor back as a python basic datatype

In [3]:
print(type(scalar.item()))

<class 'int'>


Vector

In [4]:
vector = torch.tensor([4, 6, 7])

print(vector)
vector.ndim

tensor([4, 6, 7])


1

In [5]:
vector.shape

torch.Size([3])

In [6]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [7]:
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [8]:
# 0th element
print(MATRIX[0])
print(MATRIX[0].ndim)

tensor([1, 2, 3])
1


In [9]:
# TENSOR

TENSOR = torch.tensor([[[1, 8, 3],
                        [7, 0, 1],
                        [9, 10, 45]]])

In [10]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  8,  3],
         [ 7,  0,  1],
         [ 9, 10, 45]]])
3
torch.Size([1, 3, 3])


In [11]:
TENSOR[0]

tensor([[ 1,  8,  3],
        [ 7,  0,  1],
        [ 9, 10, 45]])

In [12]:
# TENSOR_4D
TENSOR_4D = torch.tensor([
    [
      [
          [ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]
      ],

      [
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]
      ]
    ],

    [
        [
            [31, 32, 33, 34],
            [35, 36, 37, 38],
            [39, 40, 41, 42]
        ],

        [
            [ 12,  22,  23,  24],
            [ 25,  26,  27,  28],
            [ 9, 10, 11, 12]
        ]
    ],

    [
        [
            [41, 42, 43, 44],
            [25, 26, 27, 28],
            [ 29, 30, 31, 32]
        ],

      [
          [51, 52, 53, 54],
          [75, 76, 77, 78],
          [89, 80, 81, 82]
      ],
    ]
  ])
TENSOR_4D

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[21, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]]],


        [[[31, 32, 33, 34],
          [35, 36, 37, 38],
          [39, 40, 41, 42]],

         [[12, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]]],


        [[[41, 42, 43, 44],
          [25, 26, 27, 28],
          [29, 30, 31, 32]],

         [[51, 52, 53, 54],
          [75, 76, 77, 78],
          [89, 80, 81, 82]]]])

In [13]:
print(TENSOR_4D.ndim)
print(TENSOR_4D.shape)

4
torch.Size([3, 2, 3, 4])


In [14]:
print(TENSOR_4D[2][1][1])

tensor([75, 76, 77, 78])


### Random Tensor

Why random tensors?

Random tensors are important because the way many Neural networks work is, they start with tensors filled with big random numbers and work there way to adjust these random numbers to better represent data.

`Start with random numebrs --> Look at Data --> Update random numbers --> Look at Data --> Update random numbers `

Random Tensor Docs -->
https://pytorch.org/docs/stable/generated/torch.rand.html

In [15]:
## Create a random tensor of size (3, 4)
random_tensor = torch.rand([3, 4])
random_tensor, random_tensor.dtype

(tensor([[0.1924, 0.6736, 0.9098, 0.2384],
         [0.4221, 0.8210, 0.9164, 0.7748],
         [0.2226, 0.0933, 0.7738, 0.2356]]),
 torch.float32)

In [16]:
print(random_tensor.ndim)
print(random_tensor.size())


2
torch.Size([3, 4])


Create a random tensor with size of that of an image

In [17]:
random_image_size_tensor = torch.rand(size = [224, 224, 3]) # Image size = (224, 224, 3) Height x Width x Color Channels ()
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
random_image_size_tensor

tensor([[[0.9438, 0.2005, 0.9885],
         [0.2293, 0.5334, 0.8268],
         [0.2097, 0.1672, 0.6000],
         ...,
         [0.2402, 0.4608, 0.7744],
         [0.1626, 0.1413, 0.1816],
         [0.8843, 0.8452, 0.3455]],

        [[0.0629, 0.6204, 0.7453],
         [0.9275, 0.6866, 0.0059],
         [0.5639, 0.1595, 0.7091],
         ...,
         [0.8074, 0.0205, 0.0715],
         [0.1944, 0.4202, 0.5884],
         [0.0704, 0.3113, 0.5695]],

        [[0.9386, 0.4499, 0.9988],
         [0.3483, 0.1053, 0.3330],
         [0.0686, 0.8515, 0.2213],
         ...,
         [0.0036, 0.9265, 0.1625],
         [0.2935, 0.8826, 0.2162],
         [0.4746, 0.2060, 0.9279]],

        ...,

        [[0.2041, 0.7115, 0.5191],
         [0.7391, 0.2328, 0.1998],
         [0.9213, 0.1273, 0.4420],
         ...,
         [0.4495, 0.0342, 0.1693],
         [0.2007, 0.0306, 0.7222],
         [0.7010, 0.0421, 0.0256]],

        [[0.3307, 0.3379, 0.9352],
         [0.2196, 0.8035, 0.3872],
         [0.

In [19]:
exerc_random_tensor = torch.rand(size= (3,30,30) ) #3 channel color image of 30x30 pixels
exerc_random_tensor.shape, exerc_random_tensor.ndim

(torch.Size([3, 30, 30]), 3)

In [20]:
exerc_random_tensor

tensor([[[0.2385, 0.8649, 0.5515,  ..., 0.6774, 0.1685, 0.4712],
         [0.9677, 0.5434, 0.3472,  ..., 0.9295, 0.5296, 0.6044],
         [0.2759, 0.5950, 0.1069,  ..., 0.2270, 0.1753, 0.9459],
         ...,
         [0.4472, 0.9080, 0.7711,  ..., 0.9407, 0.1768, 0.8291],
         [0.3447, 0.6822, 0.4280,  ..., 0.7408, 0.2719, 0.6954],
         [0.3194, 0.2113, 0.3208,  ..., 0.3357, 0.9728, 0.6741]],

        [[0.7887, 0.1035, 0.2130,  ..., 0.0916, 0.0298, 0.3645],
         [0.3421, 0.9512, 0.3780,  ..., 0.8153, 0.3013, 0.8545],
         [0.2362, 0.5771, 0.4506,  ..., 0.6579, 0.6615, 0.9440],
         ...,
         [0.9485, 0.9421, 0.5166,  ..., 0.0808, 0.1348, 0.8446],
         [0.9224, 0.7193, 0.7220,  ..., 0.1756, 0.3959, 0.8243],
         [0.0257, 0.3301, 0.8034,  ..., 0.0103, 0.2341, 0.6958]],

        [[0.1669, 0.4686, 0.7157,  ..., 0.8165, 0.7619, 0.0695],
         [0.7154, 0.1573, 0.7729,  ..., 0.4462, 0.0350, 0.2557],
         [0.2064, 0.1961, 0.6998,  ..., 0.5432, 0.9713, 0.

##Zeros and Ones

In [21]:
#Create Tensor of all Zeros
zeros = torch.zeros(size=[3, 4])
zeros.size()

torch.Size([3, 4])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=[3, 4])
print(ones, ones.ndim)
ones * random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 2


tensor([[0.1924, 0.6736, 0.9098, 0.2384],
        [0.4221, 0.8210, 0.9164, 0.7748],
        [0.2226, 0.0933, 0.7738, 0.2356]])

#Creating a range of tensors and tensor-like

#torch.arange() --> https://pytorch.org/docs/stable/generated/torch.arange.html
#torch.zeros_like() --> https://pytorch.org/docs/stable/generated/torch.zeros_like.html
#torch.ones)like() --> https://pytorch.org/docs/stable/generated/torch.ones_like.html

In [24]:
# Create a tensor with arange
range_tensor = torch.arange(start=10, end=30, step=2)
range_tensor

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
#Create a zeros like tensor with same shape as another tensor
zeros_like_tensor = torch.zeros_like(input= range_tensor)
zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
#Create a ones like tensor with same shape as another tensor
ones_like_tensor = torch.ones_like(input= range_tensor)
ones_like_tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
float32_tensor = torch.tensor(data= [3.0, 6.0, 9.0],
                              dtype= torch.float32, # What data type is the tensor eg. float32, float16 etc.
                              device= None,         #
                              requires_grad= False,
                              )

#Three most common mistakes that happen during machine learning programming are:
1. dtype - Data type mismatch between tensors
2. size and shape - size and shape mismatch between tensors and
3. device type - Device type mismatch, Tensor not on right device

Precision in Computing

https://en.wikipedia.org/wiki/Precision_(computer_science)

In [28]:
float_32_tensor = torch.tensor(data=[3.0,6.0,9.0],
                              dtype=torch.float32,  # What is the data type of your Tensor eg. float32, float16  etc.
                              device=None,          # On which device your Tensor will reside eg. cpu, cuda
                              requires_grad=False)  # whether or not to track gradient with this Tensors operations

print(float_32_tensor)

converted_to_float16 = float_32_tensor.type(dtype=torch.float16)
converted_to_float16

tensor([3., 6., 9.])


tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor = torch.tensor(data=[8.0, 9.0, 10.0],
                               dtype= torch.float16,
                               device=None,
                               requires_grad= False)
float_16_tensor

tensor([ 8.,  9., 10.], dtype=torch.float16)

In [30]:
mul_tensor = float_32_tensor * float_16_tensor
mul_tensor

tensor([24., 54., 90.])

#Getting information from a Tensor

1. dtype - Data type mismatch between tensors --> to get datatype use tensor.dtype
2. size and shape - size and shape mismatch between tensors --> to get shape use tensor.shape3
3. device type - Device type mismatch, Tensor not on right device --> to get device on which tensor is residing, use tensor.device

In [ ]:
# Create a random tensor

a_new_tensor = torch.rand([3, 5])

print(a_new_tensor)
print(f"Data type of tensor : {a_new_tensor.dtype}")
print(f"Shape of the tensor: {list(a_new_tensor.shape)}")
print(f"Device on which tensor is: {a_new_tensor.device}")

#cuda = torch.device('cuda')
#a_new_tensor.to(cuda)

print(f"--Data type of tensor : {a_new_tensor.dtype}")
print(f"--Shape of the tensor: {list(a_new_tensor.shape)}")
print(f"--Device on which tensor is: {a_new_tensor.device}")

## Manupulating Tensors - (tensor Operations)