<a href="https://colab.research.google.com/github/amarbtsingh/first-contributions/blob/main/00_PyTorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

Creating Tensors

Scalar

In [ ]:
scalar = torch.tensor(7) # number 7 is being initialised as a scalar

print(scalar)

scalar.ndim

print(type(scalar))


tensor(7)
<class 'torch.Tensor'>


Get tensor back as a python basic datatype

In [ ]:
print(type(scalar.item()))

<class 'int'>


Vector

In [ ]:
vector = torch.tensor([4, 6, 7])

print(vector)
vector.ndim

tensor([4, 6, 7])


1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [ ]:
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [ ]:
# 0th element
print(MATRIX[0])
print(MATRIX[0].ndim)

tensor([1, 2, 3])
1


In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 8, 3],
                        [7, 0, 1],
                        [9, 10, 45]]])

In [ ]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  8,  3],
         [ 7,  0,  1],
         [ 9, 10, 45]]])
3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[ 1,  8,  3],
        [ 7,  0,  1],
        [ 9, 10, 45]])

In [ ]:
# TENSOR_4D
TENSOR_4D = torch.tensor([
    [
      [
          [ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]
      ],

      [
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]
      ]
    ],

    [
        [
            [31, 32, 33, 34],
            [35, 36, 37, 38],
            [39, 40, 41, 42]
        ],

        [
            [ 12,  22,  23,  24],
            [ 25,  26,  27,  28],
            [ 9, 10, 11, 12]
        ]
    ],

    [
        [
            [41, 42, 43, 44],
            [25, 26, 27, 28],
            [ 29, 30, 31, 32]
        ],

      [
          [51, 52, 53, 54],
          [75, 76, 77, 78],
          [89, 80, 81, 82]
      ],
    ]
  ])
TENSOR_4D

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[21, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]]],


        [[[31, 32, 33, 34],
          [35, 36, 37, 38],
          [39, 40, 41, 42]],

         [[12, 22, 23, 24],
          [25, 26, 27, 28],
          [ 9, 10, 11, 12]]],


        [[[41, 42, 43, 44],
          [25, 26, 27, 28],
          [29, 30, 31, 32]],

         [[51, 52, 53, 54],
          [75, 76, 77, 78],
          [89, 80, 81, 82]]]])

In [ ]:
print(TENSOR_4D.ndim)
print(TENSOR_4D.shape)

4
torch.Size([3, 2, 3, 4])


In [ ]:
print(TENSOR_4D[2][1][1])

tensor([75, 76, 77, 78])


### Random Tensor

Why random tensors?

Random tensors are important because the way many Neural networks work is, they start with tensors filled with big random numbers and work there way to adjust these random numbers to better represent data.

`Start with random numebrs --> Look at Data --> Update random numbers --> Look at Data --> Update random numbers `

Random Tensor Docs -->
https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
## Create a random tensor of size (3, 4)
random_tensor = torch.rand([3, 4])
random_tensor, random_tensor.dtype

(tensor([[0.5594, 0.5105, 0.6670, 0.7721],
         [0.3371, 0.8614, 0.0336, 0.7084],
         [0.4157, 0.1375, 0.2742, 0.9491]]),
 torch.float32)

In [ ]:
print(random_tensor.ndim)
print(random_tensor.size())


2
torch.Size([3, 4])


Create a random tensor with size of that of an image

In [ ]:
random_image_size_tensor = torch.rand(size = [224, 224, 3]) # Image size = (224, 224, 3) Height x Width x Color Channels ()
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.9289, 0.9331, 0.5077],
         [0.0183, 0.5874, 0.5099],
         [0.9573, 0.9993, 0.8078],
         ...,
         [0.1234, 0.8389, 0.2189],
         [0.6502, 0.2019, 0.8893],
         [0.2654, 0.5809, 0.3976]],

        [[0.0166, 0.5477, 0.2320],
         [0.9178, 0.8798, 0.5019],
         [0.7995, 0.4503, 0.5503],
         ...,
         [0.1395, 0.5197, 0.1737],
         [0.5452, 0.3704, 0.3455],
         [0.0796, 0.5413, 0.0659]],

        [[0.3992, 0.6238, 0.8062],
         [0.0528, 0.9275, 0.7350],
         [0.8925, 0.9119, 0.0976],
         ...,
         [0.2798, 0.9632, 0.9533],
         [0.1126, 0.8930, 0.3689],
         [0.8230, 0.0353, 0.6029]],

        ...,

        [[0.2499, 0.2750, 0.6234],
         [0.1626, 0.1020, 0.1411],
         [0.0694, 0.4897, 0.0845],
         ...,
         [0.2218, 0.0632, 0.0778],
         [0.6387, 0.1871, 0.1654],
         [0.7844, 0.4674, 0.3943]],

        [[0.4843, 0.3300, 0.5379],
         [0.0582, 0.1312, 0.6086],
         [0.

In [ ]:
exerc_random_tensor = torch.rand(size= (3,30,30) ) #3 channel color image of 30x30 pixels
exerc_random_tensor.shape, exerc_random_tensor.ndim

(torch.Size([3, 30, 30]), 3)

In [ ]:
exerc_random_tensor

tensor([[[0.4005, 0.3301, 0.5367,  ..., 0.4517, 0.8158, 0.5001],
         [0.5977, 0.5609, 0.9768,  ..., 0.9014, 0.2152, 0.7421],
         [0.9332, 0.4691, 0.6569,  ..., 0.0053, 0.2777, 0.4105],
         ...,
         [0.9458, 0.0191, 0.2945,  ..., 0.5127, 0.1568, 0.9152],
         [0.7736, 0.2568, 0.9831,  ..., 0.0476, 0.9998, 0.4889],
         [0.8373, 0.1826, 0.2561,  ..., 0.7575, 0.8023, 0.8121]],

        [[0.3637, 0.7017, 0.3403,  ..., 0.7013, 0.4659, 0.9225],
         [0.9583, 0.3826, 0.4452,  ..., 0.9911, 0.8528, 0.6852],
         [0.5627, 0.8050, 0.7323,  ..., 0.8013, 0.3313, 0.3992],
         ...,
         [0.7699, 0.5369, 0.1523,  ..., 0.2443, 0.7225, 0.9264],
         [0.2592, 0.4294, 0.1472,  ..., 0.9693, 0.5868, 0.3992],
         [0.7225, 0.9678, 0.4739,  ..., 0.8526, 0.0574, 0.6495]],

        [[0.9671, 0.6059, 0.3525,  ..., 0.0616, 0.4262, 0.0187],
         [0.4032, 0.9974, 0.9585,  ..., 0.4232, 0.6443, 0.4746],
         [0.1316, 0.1215, 0.0538,  ..., 0.2220, 0.9068, 0.

##Zeros and Ones

In [ ]:
#Create Tensor of all Zeros
zeros = torch.zeros(size=[3, 4])
zeros.size()

torch.Size([3, 4])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=[3, 4])
print(ones, ones.ndim)
ones * random_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 2


tensor([[0.5594, 0.5105, 0.6670, 0.7721],
        [0.3371, 0.8614, 0.0336, 0.7084],
        [0.4157, 0.1375, 0.2742, 0.9491]])

#Creating a range of tensors and tensor-like

#torch.arange() --> https://pytorch.org/docs/stable/generated/torch.arange.html
#torch.zeros_like() --> https://pytorch.org/docs/stable/generated/torch.zeros_like.html
#torch.ones)like() --> https://pytorch.org/docs/stable/generated/torch.ones_like.html

In [ ]:
# Create a tensor with arange
range_tensor = torch.arange(start=10, end=30, step=2)
range_tensor

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
#Create a zeros like tensor with same shape as another tensor
zeros_like_tensor = torch.zeros_like(input= range_tensor)
zeros_like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Create a ones like tensor with same shape as another tensor
ones_like_tensor = torch.ones_like(input= range_tensor)
ones_like_tensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
float32_tensor = torch.tensor(data= [3.0, 6.0, 9.0],
                              dtype= torch.float32, # What data type is the tensor eg. float32, float16 etc.
                              device= None,         #
                              requires_grad= False,
                              )

#Three most common mistakes that happen during machine learning programming are:
1. dtype - Data type mismatch between tensors
2. size and shape - size and shape mismatch between tensors and
3. device type - Device type mismatch, Tensor not on right device

Precision in Computing

https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
float_32_tensor = torch.tensor(data=[3.0,6.0,9.0],
                              dtype=torch.float32,  # What is the data type of your Tensor eg. float32, float16  etc.
                              device=None,          # On which device your Tensor will reside eg. cpu, cuda
                              requires_grad=False)  # whether or not to track gradient with this Tensors operations

print(float_32_tensor)

converted_to_float16 = float_32_tensor.type(dtype=torch.float16)
converted_to_float16

tensor([3., 6., 9.])


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = torch.tensor(data=[8.0, 9.0, 10.0],
                               dtype= torch.float16,
                               device=None,
                               requires_grad= False)
float_16_tensor

tensor([ 8.,  9., 10.], dtype=torch.float16)

In [ ]:
mul_tensor = float_32_tensor * float_16_tensor
mul_tensor

tensor([24., 54., 90.])

#Getting information from a Tensor

1. dtype - Data type mismatch between tensors --> to get datatype use tensor.dtype
2. size and shape - size and shape mismatch between tensors --> to get shape use tensor.shape3
3. device type - Device type mismatch, Tensor not on right device --> to get device on which tensor is residing, use tensor.device

In [ ]:
# Create a random tensor

a_new_tensor = torch.rand([3, 5])

print(a_new_tensor)
print(f"Data type of tensor : {a_new_tensor.dtype}")
print(f"Shape of the tensor: {list(a_new_tensor.shape)}")
print(f"Device on which tensor is: {a_new_tensor.device}")

#cuda = torch.device('cuda')
#a_new_tensor.to(cuda)

print(f"--Data type of tensor : {a_new_tensor.dtype}")
print(f"--Shape of the tensor: {list(a_new_tensor.shape)}")
print(f"--Device on which tensor is: {a_new_tensor.device}")

tensor([[0.9129, 0.2666, 0.6019, 0.6180, 0.5364],
        [0.4493, 0.6666, 0.0917, 0.1770, 0.9247],
        [0.3392, 0.5582, 0.9680, 0.7134, 0.7661]])
Data type of tensor : torch.float32
Shape of the tensor: [3, 5]
Device on which tensor is: cpu
--Data type of tensor : torch.float32
--Shape of the tensor: [3, 5]
--Device on which tensor is: cpu


## Manupulating Tensors - (tensor Operations)
Operations are
* Addition
* Subtraction
* Multiplication - elementwise
* Division
* Matrix Multiplication

In [ ]:
# Addition Operation - The addition operation in PyTorch requires the tensors to have the same size at all non-singleton dimensions.

#Create a Tensor

first_tensor = torch.rand(size=[3,4], dtype=torch.float16)
print("First =", first_tensor)

second_tensor = torch.rand(size=[3, 3], dtype=torch.float16, device="cpu")
print("Second =", second_tensor)

third_tensor = first_tensor + second_tensor.resize_(size=[3, 4])
print("Third = ", third_tensor)


First = tensor([[0.0283, 0.9185, 0.3848, 0.4414],
        [0.7432, 0.7607, 0.6929, 0.6509],
        [0.1953, 0.4058, 0.7275, 0.4409]], dtype=torch.float16)
Second = tensor([[0.5938, 0.3223, 0.6265],
        [0.2798, 0.1284, 0.8374],
        [0.9932, 0.3730, 0.8091]], dtype=torch.float16)
Third =  tensor([[0.6221, 1.2402, 1.0117, 0.7212],
        [0.8716, 1.5977, 1.6855, 1.0234],
        [1.0039, 0.4058, 0.7275, 0.4409]], dtype=torch.float16)


In [ ]:
fourth_tensor=torch.rand(size=(3,3),dtype=torch.float16)
print(fourth_tensor)
print(fourth_tensor + 10)

tensor([[0.2119, 0.6548, 0.8198],
        [0.3193, 0.0923, 0.2471],
        [0.4814, 0.9805, 0.4238]], dtype=torch.float16)
tensor([[10.2109, 10.6562, 10.8203],
        [10.3203, 10.0938, 10.2500],
        [10.4844, 10.9844, 10.4219]], dtype=torch.float16)


In [ ]:
fourth_tensor - 10

tensor([[-9.7891, -9.3438, -9.1797],
        [-9.6797, -9.9062, -9.7500],
        [-9.5156, -9.0156, -9.5781]], dtype=torch.float16)

In [ ]:
fourth_tensor * 10

tensor([[2.1191, 6.5469, 8.1953],
        [3.1934, 0.9229, 2.4707],
        [4.8125, 9.8047, 4.2383]], dtype=torch.float16)

In [ ]:
fourth_tensor / 10

tensor([[0.0212, 0.0655, 0.0820],
        [0.0319, 0.0092, 0.0247],
        [0.0482, 0.0980, 0.0424]], dtype=torch.float16)

### Tensor Multiplication

1. Element-wise multiplication
2. Matrix Multiplication - Dot Product

https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules when performing matrix multiplication
1. The inner dimensions must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 2) @ (2, 4)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has shape of outer dimensions

In [ ]:
#Element-wise Multiplication
%%time

tensor = torch.tensor([1, 2, 4])

print(tensor, " * ", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 4])  *  tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])
CPU times: user 3.92 ms, sys: 0 ns, total: 3.92 ms
Wall time: 3.81 ms


In [ ]:
## Matrix Multiplication
%%time
tensor1 = torch.tensor([[2, 3],
                        [4, 6]])
print("Tensor1:", tensor1)

tensor2 = torch.tensor([[4, 5, 6],
                        [1, 4, 6]])
print("Tensor2:", tensor2)

torch.matmul(tensor1, tensor2)

In [ ]:
%%time

tensor3 = torch.tensor([4, 5, 6])

print(torch.matmul(tensor3, tensor3))

tensor(77)
CPU times: user 656 µs, sys: 0 ns, total: 656 µs
Wall time: 1.36 ms


In [ ]:
%%time
value = 0
for i in range(len(tensor3)):
  value += tensor3[i]*tensor3[i]
value

### Tensor Aggregation

Finding min, max, mean , sum etc. of a tensor

In [ ]:
# Create a Tensor

tensor_x = torch.randint(high=500, size=(3, 6))
tensor_x

tensor([[154, 286, 430, 234, 291,  97],
        [266, 492,  76, 224, 272, 225],
        [275, 166, 385, 390, 325, 365]])

In [ ]:
print(f"Min : {tensor_x.min()}")
print(f"Max : {tensor_x.max()}")
print(f"Mean : {tensor_x.mean(dtype=torch.float16)}")
print(f"Sum : {tensor_x.sum()}")

Min : 76
Max : 492
Mean : 275.25
Sum : 4953


In [ ]:
torch.argmin(tensor_x,dim=1, keepdim=True)


tensor([[5],
        [2],
        [1]])

### Reshaping, Stacking, Unstacking, Squeezing and Un-Squeezing Tensors
* Reshape - reshapes an input tensor to a defined shape
* View - returns the view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - Combining multiple tensors on top of each other - (vstack) or side-by-side (hstack)
* Squeeze - Removes all `1` dimension from the tensor
* Unsqueeze - Adds `1` dimension to a target tensor
* Permute - Returns view of a tensor with the dimensions permuted (swapped) in a certain way



In [ ]:
## Create a new tensor
import torch
x = torch.arange(1, 47, 5)
x, x.shape

(tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape((1, 10))
x_reshaped, x_reshaped.shape

(tensor([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46]]), torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  6, 11, 16, 21],
         [26, 31, 36, 41, 46]]),
 torch.Size([2, 5]))

In [ ]:
# Change the view
y = torch.arange(1, 47, 5)

z = y.view(10, 1)
z, z.shape

(tensor([[ 1],
         [ 6],
         [11],
         [16],
         [21],
         [26],
         [31],
         [36],
         [41],
         [46]]),
 torch.Size([10, 1]))

In [ ]:
z[0][0] = 7
z, y

(tensor([[ 7],
         [ 6],
         [11],
         [16],
         [21],
         [26],
         [31],
         [36],
         [41],
         [46]]),
 tensor([ 7,  6, 11, 16, 21, 26, 31, 36, 41, 46]))

In [ ]:
# Stacking

tensor_normal = torch.arange(0., 3., 0.5)
tensor_normal, tensor_normal.shape

tensor_stacked = torch.stack([tensor_normal, tensor_normal, tensor_normal, tensor_normal], dim=1)
print("Normal - ", tensor_normal,tensor_normal.shape)
print("Stacked - ",tensor_stacked, tensor_stacked.shape)

tensor_stacked_2 = torch.stack([tensor_stacked, tensor_stacked, tensor_stacked], dim=2)
print("Stacked_2 - ",tensor_stacked_2, tensor_stacked_2.shape)

Normal -  tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000]) torch.Size([6])
Stacked -  tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000, 1.5000],
        [2.0000, 2.0000, 2.0000, 2.0000],
        [2.5000, 2.5000, 2.5000, 2.5000]]) torch.Size([6, 4])
Stacked_2 -  tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]],

        [[1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000]],

        [[1.5000, 1.5000, 1.5000],
         [1.5000, 1.5000, 1.5000],
         [1.5000, 1.5000, 1.5000],
         [1.5000, 1.5000, 1.5000]],

        [[2.0000, 2.0000, 2.0000],
         [2.0000, 

In [11]:
# Squeeze
import torch
tensor_sq = torch.tensor([[5, 7, 6, 8, 9, 10]])
print(tensor_sq, tensor_sq.shape)

tensor_squeezed = tensor_sq.squeeze(dim=0)
print(tensor_squeezed, tensor_squeezed.shape)

tensor_sq_stacked = torch.stack([tensor_sq],dim=2)
print(tensor_sq_stacked, tensor_sq_stacked.shape)

a = tensor_sq_stacked.squeeze(dim=2)
print(a, a.shape)


tensor([[ 5,  7,  6,  8,  9, 10]]) torch.Size([1, 6])
tensor([ 5,  7,  6,  8,  9, 10]) torch.Size([6])
tensor([[[ 5],
         [ 7],
         [ 6],
         [ 8],
         [ 9],
         [10]]]) torch.Size([1, 6, 1])
tensor([[ 5,  7,  6,  8,  9, 10]]) torch.Size([1, 6])


In [24]:
# View
print("tensor_sq --> ", tensor_sq, tensor_sq.shape)

print(tensor_sq[0], tensor_sq[0].shape)
print(tensor_sq.view(6,1))

tensor_sq -->  tensor([[ 5,  7,  6,  8,  9, 10]]) torch.Size([1, 6])
tensor([ 5,  7,  6,  8,  9, 10]) torch.Size([6])
tensor([[ 5],
        [ 7],
        [ 6],
        [ 8],
        [ 9],
        [10]])


In [32]:
# Squeeeze and Unsqueeze
import torch

tensor_base = torch.tensor([[3, 5, 6, 2, 6, 8, 9]])
print("Oriinal Tensor------\n", tensor_base, tensor_base.shape)

tensor_squeezed = tensor_base.squeeze()
print("Squeezed Tensor ------\n", tensor_squeezed, tensor_squeezed.shape)

tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=1)
print("Unsqueezed Tensor -----\n", tensor_unsqueezed, tensor_unsqueezed.shape)


Oriinal Tensor------
 tensor([[3, 5, 6, 2, 6, 8, 9]]) torch.Size([1, 7])
Squeezed Tensor ------
 tensor([3, 5, 6, 2, 6, 8, 9]) torch.Size([7])
Unsqueezed Tensor -----
 tensor([[3],
        [5],
        [6],
        [2],
        [6],
        [8],
        [9]]) torch.Size([7, 1])


In [9]:
# Permute - Returns view of a tensor with the dimensions permuted (swapped) in a certain way
# (Permute gives a view, uses same memory as the original tensor)
import torch

tensor_orig = torch.randn(size=[224, 224, 3], dtype=torch.float32) # in an image [ height, width, colour_channels]
print("Original Tensor -----\n", tensor_orig, tensor_orig.shape)

# Permute - make the colour channel as the first dimension (0th)
tensor_rearranged = tensor_orig.permute([2, 0, 1]) # Shifts axis 0->1, 1->2, 2->0
print("Permuted Tensor -----\n", tensor_rearranged, tensor_rearranged.shape)

# Exercise - change a value in the new tensor & see if is reflected in the original tensor as well
tensor_rearranged[0][1][0] = 25.0

print("Original Tensor -----\n", tensor_orig, tensor_orig.shape)
print("Permuted Tensor -----\n", tensor_rearranged, tensor_rearranged.shape)

# Check if the changed value reflected in the original tensor
if tensor_orig[1][0][0] == 25.:
  print("Value changed!....")

Original Tensor -----
 tensor([[[ 2.2299e-01, -2.1468e-01, -1.2113e-01],
         [-7.4802e-01,  8.0236e-01,  1.7328e+00],
         [ 1.3447e+00, -6.1208e-01,  2.0023e+00],
         ...,
         [-1.2441e+00, -3.2099e-01, -1.0835e-01],
         [ 2.3494e+00, -1.3950e+00,  4.3053e-01],
         [ 1.4597e+00,  2.3039e-01,  2.5539e-01]],

        [[ 8.1420e-01, -1.3279e+00,  9.7823e-02],
         [-7.9173e-01,  2.3258e-03, -6.3672e-01],
         [ 4.2282e-01, -9.2696e-01, -5.0053e-01],
         ...,
         [-5.3758e-01,  1.3077e+00, -1.6995e+00],
         [-7.4405e-01, -7.0873e-01, -8.4812e-01],
         [-1.1068e+00,  1.1063e+00, -1.0064e+00]],

        [[ 9.2988e-01,  1.0248e+00,  4.6456e-02],
         [ 2.9698e-01,  6.9988e-01,  2.5220e+00],
         [-1.5928e+00, -3.7290e-01,  3.6931e-01],
         ...,
         [ 1.1830e+00,  2.7332e+00,  2.6489e+00],
         [-1.1111e+00, -6.2876e-01,  4.6798e-01],
         [ 4.8464e-01,  5.4669e-01,  1.3120e+00]],

        ...,

        [[-2.12