<a href="https://colab.research.google.com/github/amarbtsingh/first-contributions/blob/main/Tensor_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
tensor_one_d = tf.constant([2, 0, -3, 10, 11],dtype="int8")
print(tensor_one_d)

tf.Tensor([ 2  0 -3 10 11], shape=(5,), dtype=int8)


In [10]:
tensor_two_d = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [16]:
tensor_three_d = tf.constant([
  [[1,2,3,4],
   [4,5,6,7]],
  [[8,9,10,11],
   [12,13,14,15]],
  [[16,17,18,19],
   [20,21,22,23]]
])
print(tensor_three_d)

tp = tensor_three_d.shape
print(tp)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)
(3, 2, 4)
3


In [19]:
tensor_four_d = tf.constant([
    [
[[ 1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]],

[[ 21, 22, 23, 24],
[25, 26, 27, 28],
[9, 10, 11, 12]],

[[ 31, 32, 33, 34],
[35, 36, 37, 38],
[39, 40, 41, 42]]
],
[
[[ 1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]],

[[ 21, 22, 23, 24],
[25, 26, 27, 28],
[9, 10, 11, 12]],

[[ 31, 32, 33, 34],
[35, 36, 37, 38],
[39, 40, 41, 42]]
]
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[21 22 23 24]
   [25 26 27 28]
   [ 9 10 11 12]]

  [[31 32 33 34]
   [35 36 37 38]
   [39 40 41 42]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[21 22 23 24]
   [25 26 27 28]
   [ 9 10 11 12]]

  [[31 32 33 34]
   [35 36 37 38]
   [39 40 41 42]]]], shape=(2, 3, 3, 4), dtype=int32)


In [23]:
tensor_identity = tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=(2,4,),
    dtype=tf.dtypes.int8,
    name=None
)
print(tensor_identity)

tf.Tensor(
[[[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]]


 [[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]
   [0 0 0 1]]]], shape=(2, 4, 4, 4), dtype=int8)


In [25]:
tensor_fill_3d = tf.fill(
    [2,3,4,5], 7, name=None, layout=None
)
print(tensor_fill_3d)

tf.Tensor(
[[[[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]

  [[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]

  [[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]]


 [[[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]

  [[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]

  [[7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]
   [7 7 7 7 7]]]], shape=(2, 3, 4, 5), dtype=int32)


In [28]:
tensor_ones_like = tf.ones_like(tensor_fill_3d)
print(tensor_ones_like)

tf.Tensor(
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]], shape=(2, 3, 4, 5), dtype=int32)
